### ISSUE TITLE
Add release.txt for release

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#10]
Following this [conversation](https://github.com/TaddyLab/politext/issues/347#issuecomment-247199728) we want to add a `/release/release.txt` file as a release asset that will keep track of the file list, drive path, and time stamp in each release. 

This task includes updating release procedure in congress_text and congress_members.

**Comment by lboxell** [comment]
In order to programmatically create a release asset, I think we'll need to use github's tokens (see https://developer.github.com/v3/ where they list the 3 types of authentication. I don't think user/pass will work because we use two-factor authentication). 

Releases should only happen once per issue, so it shouldn't too big of an issue to require a user to enter the token each time. (We should probably confirm the user enters a valid token before posting a release to drive/github). Over time, we should be able to setup a system where we securely store the token some place on a machine, which avoids having to type it manually.

@gentzkow,

For the purpose of this task, are you fine going ahead with an implementation that requires the user to manually enter their github token every time they want to post an asset to a release?

**Comment by gentzkow** [comment]
Yup. I'm fine with the manual implementation. Let's just not somewhere the
procedure for generating the github token.

**Comment by lboxell** [comment]
Scratch code:

See: http://stackoverflow.com/questions/25349296/how-to-release-automatically-your-artifact-to-github
```
curl POST -d  '{
  "tag_name": "test",
  "target_commitish": "master",
  "name": "test",
  "body": "Description of the release",
  "draft": false,
  "prerelease": false
}' https://[TOKEN]:@api.github.com/repos/gslab-econ/template/releases

## NOTE: Need to attain release id programmatically

curl -# -XPOST -H "Authorization:token [TOKEN]" -H "Content-Type:text/markdown" --data-binary @assets.txt https://uploads.github.com/repos/gslab-econ/template/releases/4222249/assets?name=assets.txt
```

**Comment by lboxell** [comment]
Have python code that will create a release, find the release id, and upload a .txt file to the release as an asset. 

Need to: 
 - Write code to create the .txt file that lists the assets stored in Drive and their relative locations.
 - Integrate with scons build procedure for releases


Scratch code:
```
import requests, json, re

token = [TOKEN]
tag_name = 'test2'
releases_path = 'https://%s:@api.github.com/repos/gslab-econ/template/releases' % token

s              = requests.session()

## Create release
payload = {'tag_name':tag_name, 'target_commitish':'master', 'name':tag_name, 'body':'Description of release', 'draft':'FALSE', 'prerelease':'FALSE'}
j = json.dumps(payload)
j = re.sub('"FALSE"', 'false', j)
s.post(releases_path, data = j)

## Get release ID
json_releases  = s.get(releases_path)
json_output    = json_releases.content
json_split     = json_output.split(',')
tag_name_index = json_split.index('"tag_name":"%s"' % tag_name)
release_id     = json_split[tag_name_index - 1].split(':')[1]

## Post release asset
file_name = 'assets.txt'
files = {'file' : open(file_name, 'rb')}
header = {'Authorization':'token %s' % token, 'Content-Type':'text/markdown'}
upload_path = 'https://uploads.github.com/repos/gslab-econ/template/releases/%s/assets?name=' % release_id + file_name

s.post(upload_path, files = files, headers = header)
```

**Comment by lboxell** [comment]
@M-R-Sullivan,

Can you PR this? One thing to note is that the gdrive_assets.txt file isn't very pretty. It has some meta data that gets attached to it for some reason and I'm not exactly sure how to prevent it. Since this doesn't impact any of the functionality, I'm not sure it's a critical issue to spend time on, but feel free to disagree if you think otherwise. 

Also, I haven't updated the congress_text and congress_members repos yet because I figured it would be best to have this code PR'ed before updating those repos.

Pull request [here](https://github.com/gslab-econ/template/pull/11). 

__Issue Summary:__
Updated gslab_scons.py to attach a 'gdrive_assets.txt' file to the GitHub release whenever we have large files released to google drive. The txt file documents the location where the files are stored in google drive.

**Comment by M-R-Sullivan** [comment]
@lboxell - Of course. Thanks for the info.

**Comment by lboxell** [comment]
Pull request [here](https://github.com/gslab-econ/template/pull/11). 

__Issue Summary:__
Updated gslab_scons.py to attach a 'gdrive_assets.txt' file to the GitHub release whenever we have large files released to google drive. The txt file documents the location where the files are stored in google drive.  

Follow up tasks for updating congress_text and congress_members created:
https://github.com/gslab-econ/congress_members/issues/2
https://github.com/gslab-econ/congress_text/issues/6

**Comment by stanfordquan** [comment]
Slightly pedantic comment - can we rename `uploadAsset` to `upload_asset` to match our naming convention? Same for `Release`.

**Comment by lboxell** [comment]
Pull request for name changes [here](https://github.com/gslab-econ/template/pull/14)

Original summary: [here](https://github.com/gslab-econ/template/issues/10#issuecomment-250524691)
