### ISSUE TITLE
Discuss cost to update active repositories to 4.1.0

### ISSUE THREAD

**Issue by arosenbe** [gslab-econ/template#102]
Follow-up to https://github.com/gslab-econ/gslab_python/issues/134#issuecomment-362427175. 

> I'd like you guys to give us an assessment of how much effort it would be to convert each of our currently active repositories to the new format. Based on that we can prioritize for which it is worth paying that fixed cost.

**Comment by arosenbe** [comment]
My experience is that an update (4.0.1 -> 4.1.0) takes ~1 hour, and then there's the time to re-run everything. Does that match your experience @stanfordquan? 

We should also think about how much time it would take some to update if they didn't build all the tools.

**Comment by Shun-Yang** [comment]
Another valuable question is: what's the time estimates to update form 3.0.5 -> 4.1.0

**Comment by arosenbe** [comment]
My guess is that it's about similar. Most of my time was spent splitting the repository into two SCons directories and updating the SConstructs. Both of those should take about the same for 3.0.5 and 4.0.1.

**Comment by stanfordquan** [comment]
From 3.0.5 to 4.1.0 in a big repository (e.g. ad-price-drivers), ~1hr + code run would be a very optimistic number. Took me about >3hrs + code run. 

This is because it's not as if you do stuff and then you let code run and then boom everything works. There are some inefficiencies that's introduced by the fact that you might have code run halfway through and then it breaks, at which point you might need to fix other things upstream.

Furthermore, when we do this kind of update, features that we introduced to make sure we have a "good" SCons build like target-checkers can catch things that the repo has done wrong in the past and then we will need to fix those things. Time spent on that is necessary but should be added to the estimate.

From 4.0.1 to 4.1.0, ~1hr + code run seems reasonable subject to the things above.

**Comment by arosenbe** [comment]
Can you refresh my memory, what are the big differences from 3.0.5 to 4.0.1?

**Comment by stanfordquan** [comment]
@arosenbe , release notes [here](https://github.com/gslab-econ/template/releases).

**Comment by stanfordquan** [comment]
^ I correct my comment above. It took me about 3hrs + code run to do everything on ad-price-drivers. It does seem that the changes mostly are from going up to `4.1.x` from `4.0.0` since we did a lot more changes in `template` there. 

Of course it depends on the number of subdirectories and the state of the local `build` folder.

**Comment by stanfordquan** [comment]
In our meeting today we determined that this task will take about a 1.5-day sprint with all hands on deck (with some additional time the following day for code run). Here are the current repos:

Congress_text
Congress_members
Newsworthy
Media_productivity
Media_productivity_events
LDC_NYTimes (I (QL) will manage this but I need to clean up the code first)

Inactive repo:
Vandy-tv
Age-polar

**Comment by stanfordquan** [comment]
@gentzkow @jmshapir please see the comment above. Thanks!

**Comment by jmshapir** [comment]
I would suggest we prioritize these and plan to spend two days starting with the most important. That way, if we fail to finish in two days, we've dealt with the highest priority cases.

A proposed prioritization from highest to lowest:
* media_productivity
* media_productivity_events
* LDC_NYTimes

Ones I would propose we skip or hand off:
* newsworthy-->Updating this can be handed to Luis
* congress_text-->Data have already been released 
* congress_members-->Cousin of Congress_text

Of course I would be fine adding congress_text and congress_members to the bottom of the to-do pile. If everything is smooth and those take little time I don't have any objection to updating them.

**Comment by gentzkow** [comment]
I agree with that.

Are we omitting ad_price_drivers because it's already up to date?
What about divergence and blp_instruments?

The latter two seem high priority as well. The blp one can be handed off to Nano.

**Comment by stanfordquan** [comment]
Ad_price and Divergence are already up to date. I forgot about blp_instruments.

**Comment by Shun-Yang** [comment]
@stanfordquan divergence has not been updated yet.

**Comment by stanfordquan** [comment]
Ah yes my bad... sorry, pre-coffee comment.

**Comment by jmshapir** [comment]
So are we saying something like the following?

For gslab team, from highest to lowest priority:
* divergence
* media_productivity
* media_productivity_events
* LDC_NYTimes

To hand off:
* newsworthy-->Luis
* blp-instruments-->Nano

To skip, or do if easy and there is time left over:
* congress_text
* congress_members

**Comment by stanfordquan** [comment]
Looks good to us!

**Comment by gentzkow** [comment]
me too!

**Comment by arosenbe** [comment]
Haven't started on implementation.

**Comment by jmshapir** [comment]
I would be fine with doing it after politext is submitted. It might also work to borrow some time from divergence to work on this now, depending on the results of [divergence/#60](https://github.com/gslab-econ/divergence/issues/60).

**Comment by gentzkow** [comment]
My vote would have been to do this sooner rather than later. I think we've always found it's better to invest in keeping current projects up to date on code structure and quality rather than deferring and then having to do big clean ups later.

Since media productivity and LDC_nyt are less front burner projects at the moment, one possibility would be to execute divergence and the hand off repos now, and then come back to media_productivity and LDC_nyt once politext is done.

**Comment by jmshapir** [comment]
@gentzkow I'm fine kicking off the hand-off repos right now, and I'm also good with leaving media productivity and LDC_nyt for post-politext.

On divergence what you're proposing is likely fine, but I'd want to talk through the schedule there because we have some deadlines. Happy to discuss anytime.

**Comment by gentzkow** [comment]
OK. @stanfordquan: Remind me how much time we're talking about to clean up divergence? I would have thought it would be pretty small given there's limited data building & analysis.

**Comment by stanfordquan** [comment]
@gentzkow I expect about 3 hours + code run and debugging (@arosenbe agrees).

**Comment by gentzkow** [comment]
Great. @jmshapir: I would vote we execute this.

**Comment by jmshapir** [comment]
@stanfordquan [I asked him](https://github.com/gslab-econ/divergence/issues/57#issuecomment-389278684). If he confirms, then it's fine by me to go ahead [as you propose](https://github.com/gslab-econ/template/issues/102#issuecomment-389276707).

I also think he will be done shortly so it may not make much difference either way.

**Comment by jmshapir** [comment]
@stanfordquan IA [confirms](https://github.com/gslab-econ/divergence/issues/57#issuecomment-389404882) that he is only touching that one file. So feel free to proceed whenever you like. Once we start, let's try to finish quickly so that we don't have the repo in limbo as we do other work.

**Comment by jmshapir** [comment]
All: have we kicked off the re-org of the hand-off repos?

**Comment by stanfordquan** [comment]
@jmshapir , we have not. I propose that while we wait for the politext cluster complications to resolve, I can start on media-productivity. We also have a refactoring task on the outline for media-productivity and this seems like the right time for that.

**Comment by jmshapir** [comment]
@stanfordquan I meant the ones listed as "to hand off" [here](https://github.com/gslab-econ/template/issues/102#issuecomment-377598770). I think our plan was to have Luis/Nano start on those ASAP. I think we can do that before we start on ```media-productivity```.

**Comment by Shun-Yang** [comment]
Update: have not done any work on this in the last two weeks.

**Comment by jmshapir** [comment]
@Shun-Yang just confirming that we have asked Luis & Nano to update their respective repos?

**Comment by Shun-Yang** [comment]
@jmshapir I don't think we did. We will send an email to them now and start on this process.

**Comment by jmshapir** [comment]
Great, thanks @Shun-Yang. If these "hand-off" repos require more than minimal input from you or @stanfordquan, let me know. I'm assuming all that Luis/Nano will need from you both is a pointer.

**Comment by stanfordquan** [comment]
Email notification sent to Luis/Nano.

**Comment by gentzkow** [comment]
@Shun-Yang @stanfordquan @arosenbe: Can you give me an update on status of this task?

As some vacation fun, I am playing around with some ideas that may lead to some changes in the template. If there are any repos we haven't yet started updating I would suggest that we hold off until I'm back in early July.

**Comment by stanfordquan** [comment]
I sent a notification to Luis/Nano regarding the hand-off repos on June 11th but haven't heard anything back. We re-opened ad-price-drivers due to the README and .gitattribute issues. Other than that we haven't worked on the remaining repos 

media_productivity
media_productivity_events
LDC_NYTimes

yet. I think there will be a gap between wrapping up politext tasks and starting production in which I can update those repos.

**Comment by gentzkow** [comment]
OK. Thanks. Send me a ping before starting work on other repos.

**Comment by arosenbe** [comment]
Haven't started work on the other repos. Haven't heard anything about grad RAs making updates.

**Comment by Shun-Yang** [comment]
Update: No work on this from me in the past 2 weeks.

**Comment by Shun-Yang** [comment]
Update: I don't think the following repos have been upgraded: 
- media_productivity
- media_productivity_events
- LDC_NYTimes

Nor did we hear back from grad RAs about upgrading their repos.

**Comment by DavidRitzwoller** [comment]
No work on this in the past 2 weeks

**Comment by mengsongouyang** [comment]
No work on this yet

**Comment by DavidRitzwoller** [comment]
No work on this in the past 2 weeks

**Comment by DavidRitzwoller** [comment]
No work on this in the past 2 weeks

**Comment by DavidRitzwoller** [comment]
@jmshapir The following three repos haven't been updated. How would you like us to prioritize this?

- media_productivity
- media_productivity_events
- LDC_NYTimes

**Comment by jmshapir** [comment]
@gentzkow I am happy to leave this as is but also ok with updating them if you prefer. Your last comment on this was [here](https://github.com/gslab-econ/template/issues/102#issuecomment-386027186).

**Comment by gentzkow** [comment]
At this point I prefer to wait. As a side project Zong, Jacob, and I have been working on a simplified (non-SCons) repo structure to use with co-authors and I think there's a chance we may want to adopt a version of that for some of these repos. In any case, we can revisit at the point where we're doing a lot of active work in these repos.

I think we can go ahead and close out this thread.

**Comment by Shun-Yang** [comment]
@gentzkow sounds good. 

Closing the issue. (@arosenbe @qlquanle you can sleep easy now.)
