### ISSUE TITLE
Revisiting whether to put plots and tables in release

### ISSUE THREAD

**Issue by jmshapir** [gslab-econ/template#49]
@gentzkow what do you think about revisiting the decision not to put plots and tables in release?

I like being able to call all the inputs to the draft and slides via git for working offline on planes etc. and just for greater portability.

(Arguably these are part of the formal release of a paper in the sense that image files are typically required for typesetting anyway.)

**Comment by gentzkow** [comment]
Yes. I had the some frustration trying to compile the draft.

I have an alternative solution in mind that I was planning to discuss with you once we turn to reviewing the template. I would like to have a top-level division of the repo into something like

/data/
/analysis/
/draft-slides/

where each of these is self-contained with its own SConstruct. There would then be a manual export step to link /data/ -> /analysis/ and /analysis/ -> /draft-slides/ that's the same as what we use if we're pulling in data from a separate repository; so the tables and figures would be committed as essentially raw data in the /draft-slides/ sub-repo.

This would get us to where if we only care about editing the draft and slides, we can compile happily with scons offline without rebuilding any of the analysis *and* without having all the R packages and other prereqs in place. I've been annoyed that when I want to just edit and compile a draft I have to spend a bunch of time getting everything to where those prereqs are satisfied.

I also like this format because it makes it easy to adjust the /draft-slides/ sub-repo to fit tastes of different co-authors. E.g., we can replace scons in /draft-slides/ with a simple shell script, or move /draft-slides/ out of Github into Dropbox without changing any of the rules.

**Comment by jmshapir** [comment]
Understood. I like the plan of discussing when we turn to the template. I will close until then.
