### ISSUE TITLE
Scons logging for windows

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/template#5]
> As for implementation, we would add a log builder function to gslab_socns.py. The function would detect the operating system and use switches to appropriately redirect the stdout and stderr streams. For mac and linux, we can use my current implementation to send all output to the terminal and to a log. For windows, we would send all output to a log and not worry about printing the output.

**Comment by arosenbe** [comment]
@lboxell You can find my prior work on this task in the new branch `issue5starter`.

**Comment by arosenbe** [comment]
I have tested the log builder function on windows using @stanfordquan's laptop, and it works as intended. There were problems with the C compiler that prevented scons from production output, but these problems were appropriately captured in the log. I think we will need a new issue to get scons running on windows.

**Comment by arosenbe** [comment]
@lboxell After some more testing I have two takeaways. First, the initial pass at redirection did not redirect the stderr stream for windows. The commit above takes care of this. Second, there is no redirection of the stderr streams for the sconscripts. This is a problem because the `sconstruct.log` will record that an error occurred, but the actual error will be printed to the terminal and not recorded in any log. I recommend we tackle this in another issue.

**Comment by lboxell** [comment]
Great, thanks @arosenbe.

@stanfordquan, Could you PR this? See [here](https://github.com/gslab-econ/template/pull/6). 


Summary of task:
Basic sconstruct logging implemented for windows to redirect std.error and std.out to log file (but not console) and wrapper function created. Sconscript logging still has std.error vs std.out issues this is noted in admin wiki.  This wrapper function should be implemented into gslab_scons as a part of @admin/#67.

**Comment by lboxell** [comment]
Closing task.
