### ISSUE TITLE
Track problems with installation of die repo 

### ISSUE THREAD

**Issue by arosenbe** [gslab-econ/template#8]
This issue tracks problems that arise during installation of the [die repo](https://github.com/fgwlab-econ/die) by fgwlab (note that the repo is private). Once all users are able to run the die repo, the problems tracked here will be turned into a proposal on how to improve the template. The proposal should be delivered to @gentzkow.

**Comment by arosenbe** [comment]
One PI was unable to run `scons output/paper/mortality.pdf` from the root of the repo. The issue occurred because lyx had not been added to the PATH. The current [readme](https://github.com/fgwlab-econ/die/blob/d525f0049c9ac60f9c458caf045191b1b681b1a3/README.md) says that lyx should be added to the path but no instructions are given on how to do that.

**Comment by gentzkow** [comment]
Note that one thing we have on the outline is to add code to SConstruct
that will test whether prerequisites are installed. So rather than giving a
hard-to-interpret error on running `scons output/paper/mortality.pdf` it
would give you a nice error saying that Lyx cannot be called from the
command line.

What's odd with this case is that Amy and Heidi would need to have Lyx
callable from the command line in order to run make.py.

**Comment by arosenbe** [comment]
I agree that it is odd. I thought the error might be related to the use of a new computer or account, but Heidi confirms that is not the case. 

She did have trouble compiling a paper using `make.py` last June, and she forwarded me a thread she had with Andrés about that. The problem was related to the transfer of svn to Stanford's servers. Though, it's not exactly clear to me how it was resolved.

My best guess is that LyX had been manually added to the PATH at some point, and then something reset the PATH along the way. I can dig further, but I'm not sure how fruitful it will be and I don't want to use more of Heidi's time on this than necessary.

**Comment by gentzkow** [comment]
Thanks. No need to dig further.

**Comment by arosenbe** [comment]
## New Issue

An issue occurred when @paultfriedrich1 tried to add an SHH key to access GitHub repositories on the NBER servers. He was able to generate a key, but it was not clear that the ssh client had been enabled. This seems to be an issue with NBER, not GSLab, because we have been able to create SSH keys on RCC and Sherlock.

**Comment by arosenbe** [comment]
## Issue 3

@sarah271 wrote with four issues:

  *  How do we run scons on windows?
  *  How do we resolve conflicts if the branch of a pull request reports conflicts (instead of the "squash and merge")?
  *  Matt's manual mentions we can make branches off branches and we can't figure out how. That may be irrelevant for our workflow, but more importantly our observation is that if we use the "cloned" repository on the desktop we can only access one branch at a time (either master, or a branch we created), but we cannot change between the two. And if we've made a branch, it's neither obvious nor even clear that we can be certain we are working in the branch instead of master.
  *  How do we revert (or check which version we have)?

Work is ongoing.

**Comment by paultfriedrich1** [comment]
Given the assumption that it's possibly an NBER problem, I emailed Mohan with the question at hand in Issue 2. I will post an update when he responds.

Best,
Paul

**Comment by paultfriedrich1** [comment]
Hi Adam,

I was able to solve my problem this morning. For whatever reason, the method suggested by the GitHub help page [here](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-linux) didn't quite work on my machine. Under the "Adding Your SSH key to the ssh-agent" header, instead of running `eval "$(ssh-agent -s)"`, which mysteriously kept giving me an `Illegal variable name.` error, I instead typed `ssh-agent`, which produced the output:
```
setenv SSH_AUTH_SOCK /tmp/ssh-kuKHP12132/agent.12132;
setenv SSH_AGENT_PID 12133;
echo Agent pid 12133;
```
(I don't understand why the number in the first line is different from the numbers in the second and third lines.)

I then entered those commands one by one into my terminal, which seemed to successfully activate ssh-agent, and then was able to follow the remainder of the GitHub guide from there. Thanks so much for your help yesterday!

Best,
Paul

**Comment by sarah271** [comment]
Hi Matt,

No worries! I'm in no way offended to receive lmgtfy
<http://lmgtfy.com/?q=resolve+conflicts+in+github>emails. :)

The readme.md for the die repository says the scons instructions are for OS
X. I have to do Acumen training things today, but I'll try out scons before
Monday and see if the Windows set up is straightforward. If it's not, I'll
be sure to record what works (assuming I can figure it out) and pass that
on.

Thanks! That was helpful about resolving conflicts. I got the impression
that I could edit it within github desktop (since it has those color coded
text file versions are visible and really easy to track conflicts in) but
it seems that isn't the case; but I need to play with it a little bit to
clarify what set of approaches work. I'm going to toy with this and then
write a "Github for the github challenged" cheatsheet to circulate on our
side.

Cheers,
Sarah

**Comment by gentzkow** [comment]
Great. Sorry about those instructions. It's possible that the current
version of the scons scripts has some non-windows-friendly bits floating
around, so definitely let me know if you hit bugs. (Though I have given Amy
permission to *not* use scons at all so it may be moot. : )  )

On the merging, there are a bizillion GUI merge tools for Git that should
work like what you're hoping the client would do. We just haven't gotten
around to testing them and finding one we like. See e.g. the list at the
end of this post
<https://developer.atlassian.com/blog/2015/12/tips-tools-to-solve-git-conflicts/>
.

Another option we may want to think about for the NBER team is using a more
full-featured client like Tower
<https://www.git-tower.com/learn/git/ebook/en/command-line/tools-services/diff-merge-tools>.
The Github GUI is really designed as a bare-bones tool to be used in
conjunction with the command line -- it doesn't give you access to all Git
functions, and its features are limited. I have not used Tower (or its
competitors), but it looks like they have nice visual merges built in and
given that their page begins with "a step-by-step course for the complete
beginner" it looks promising for our target audience. : )

**Comment by arosenbe** [comment]
## Issue 4

@heidiliewilliams cannot open the GitHub Desktop application due to (I believe) a problem with git-lfs. Uninstalling and reinstalling GitHub Desktop did not resolve the issue. I've suggested removing and recloning the die repository. A bit of the error message is below.

```
Process:               GitHub Desktop [828]
Path:                  /Users/USER/Desktop/GitHub
Desktop.app/Contents/MacOS/GitHub Desktop
Identifier:            com.github.GitHub
Version:               One Type Remains (221)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           GitHub Desktop [828]
User ID:               501

Date/Time:             2016-09-20 14:14:35.990 -0400
OS Version:            Mac OS X 10.11.6 (15G31)
Report Version:        11
Anonymous UUID:        F7001368-9675-00E8-707D-1011BCDCAB5A


Time Awake Since Boot: 920 seconds

System Integrity Protection: enabled

Crashed Thread:        9  Dispatch queue:
com.ReactiveCocoa.RACScheduler.backgroundScheduler

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception
'NSInternalInconsistencyException', reason: 'Invalid parameter not
satisfying: gitLFSInfo != nil'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff89c454f2
__exceptionPreprocess + 178
1   libobjc.A.dylib                     0x00007fff99b5bf7e
objc_exception_throw + 48
2   CoreFoundation                      0x00007fff89c4a1ca +[NSException
raise:format:arguments:] + 106
3   Foundation                          0x00007fff8961c856
-[NSAssertionHandler
handleFailureInMethod:object:file:lineNumber:description:] + 198
4   GitHub Desktop                      0x000000010ef8c034
-[GHGitLFSDiffViewModel
initWithDiffDelta:gitLFSInfo:repository:objectDownloader:] + 502
5   GitHub Desktop                      0x000000010ef6c775
__58+[GHDiffViewModel
diffViewModelForGitLFSDelta:connection:]_block_invoke_2163 + 374
6   ReactiveCocoa                       0x000000010f4816ac
__36-[RACStream(Operations) flattenMap:]_block_invoke_2 + 92
7   ReactiveCocoa                       0x000000010f492c1d
__29-[RACSignal(RACStream) bind:]_block_invoke131 + 125
8   ReactiveCocoa                       0x000000010f4adb8f
-[RACSubscriber sendNext:] + 239
9   ReactiveCocoa                       0x000000010f4c5d47
-[RACPassthroughSubscriber sendNext:] + 439
```

**Comment by arosenbe** [comment]
@gentzkow, [here](https://github.com/gslab-econ/template/blob/6a4016bf6d1ded061294a66b26a01d5a1b39e8e4/issues/8-postdie/template-8.md) is the current markdown with proposals based on what we learned in this task. 

As a followup, do you have an opinion on the appropriate place to store the deliverable? It is currently in an issues subdirectory off of the issue8-postdie branch. I'm hesitant to use this storage system in master because future repositories produced from the template won't need to see this deliverable. I asked the other RAs and we produced a list of possibilities (and their problems):
  *  Putting the contents on the wiki (might get cluttered)
  *  Attaching a pdf (poor formatting and difficult to edit)
  *  Posting a comment (too long and not portable)

**Comment by gentzkow** [comment]
Why don't we put it in the /issues/ subdirectory of the admin repo (e.g.,
could be /issues/template-8/). Then we can link to it from the current task
and also add a note to the admin outline saying we should implement these
suggestions.

**Comment by arosenbe** [comment]
@M-R-Sullivan can you PR? 

The link to the deliverable in `admin/issues/` is [here](https://github.com/gslab-econ/admin/blob/1b53bea231401ba04b26193866b78d98fcdefffa/issues/template-8/template-8.md). The wiki page is [here](https://github.com/gslab-econ/admin/wiki/Outline).

**Comment by M-R-Sullivan** [comment]
@arosenbe - Yes, I can. Thanks for the links!

**Comment by M-R-Sullivan** [comment]
@arosenbe - I think that your markdown concisely reports this thread's important nuggets of knowledge and makes reasonable proposals. Additionally, your addition to the outline is appropriate. Two comments: 
- The note re: using `ssh-agent` in the markdown is a bit unclear, as GitHub's instructions also recommend use of `ssh agent`, albeit in a different way. I think that including the procedure described in this comment (or a link to the comment) so that the problem's solution is clear would be nice. 
- The markdown suggests that we add a note to the RA manual on adding executables to the path. I think we should avoid including general computer instructions in the manual but that a link to a site explaining how to set up programs in the PATH would be useful.

**Comment by arosenbe** [comment]
Thanks @M-R-Sullivan. Would you mind taking a look at an updated deliverable [here](https://github.com/gslab-econ/admin/blob/9283d74628ecba0db24b4efc31495b0811ffd1ac/issues/template-8/template-8.md). If you approve my changes, I'll update the link on the wiki and close.

**Comment by M-R-Sullivan** [comment]
@arosenbe Looks good!

**Comment by arosenbe** [comment]
The deliverable with proposed changes based on the thread above is [here](https://github.com/gslab-econ/admin/blob/9283d74628ecba0db24b4efc31495b0811ffd1ac/issues/template-8/template-8.md). A link has also been added to the outline on the admin wiki [here](https://github.com/gslab-econ/admin/wiki/Outline).
