### ISSUE TITLE
Integrate make_provenance into SConstruct

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/template#86]
We should be running `make_provenance()` every time we run SCons.

**Comment by arosenbe** [comment]
@stanfordquan, I think this issue affects the way we're making the provenance.  

My understanding is that each `scons` run now requires us to produce a provenance of all the data sources we point to. If that's the case, then the "find_for_me" and append features built into make_provenance are less valuable. We don't need to look for old provenances from our data pipeline if we're making new provenances with each run. What do you think?

**Comment by arosenbe** [comment]
We know that `make_provenance` should be run each time we run `scons`. We have different understandings of what it should do:
* Create a `provenance` using the first N files in a directory. Append to this `provenance` all other provenances within the directory and any external provenances we point to. This creates a record of the inputs as we expect them to be. 
* Create a `provenance` using the first N files in a directory. Create the same sort of provenance for all the input directories we (somehow) point to. Don't overwrite the provenances in those input directories, but do append their new provenances to `provenance`. This creates a record of the inputs as they are at runtime. 
 
---
`provenance` in code is final the output of the `make_provenance` function run after `SCons`. Without code, provenance refers to some other provenance file.

**Comment by stanfordquan** [comment]
As I see it, 2) has the benefit that if someone, say, deletes a line in the data file after having pulled a local version, then the "new" provenance will not match the existing provenance. 

However, I think that 2) will be difficult to code up/ enforce, because when you pull an external resource you will have to either pull the full directory or recreate the directory structure somehow so that the environment in which `make_provenance()` runs has to be exactly the same (otherwise you can't compare the "new" and the existing provenance). So for example 

a) you can't pull just a subset of a release directory

b) if you pull `release` and `release/lg` from two different places you have to recreate the folder structure

c) you have to specify each of these input resources and their folder structure in some manner

**Comment by stanfordquan** [comment]
@gentzkow , after our lunch discussion about `make_provenance()` we have some thoughts typed up in the two comments above. Please let us know your thoughts. Thanks!

**Comment by gentzkow** [comment]
What I had in mind is closer to (2).

To help focus this discussion, let's imagine a situation where we have a repository `downstream` that points to two external directories `upstream_raw` and `upstream_derived`. These are stored on Dropbox and the user of `downstream` points to them by setting the path to their local copies in `config_local`.

* The most important function of `make_provenance()` I had in mind is that it runs whenever we execute the SConstruct of `downstream` it records the state of (the local copies of) `upstream_raw` and `upstream_derived` and stores them in `downstream`'s /release/ directory. This way when a run of `downstream` is committed to Github, a subsequent user can always look and see what inputs were used to produce the output in /release/.

* A second function I think would be useful is what we are currently doing with the state of repo log: recording in /release/ the full contents of the repo at the end of the SConstruct run, including the contents of /release/lg/ and /build/. This way when a run of `downstream` is committed to Github, a subsequent user can always look and see what the complete outputs were. I would imagine that the algorithm for doing this should be the same as for `make_provenance`.

* On further reflection, I do not think it is necessary to store provenance files in raw directories recording the state of their contents. These will be redundant since when downstream repos point to these directories they will create the provenance on the fly.

* For derived directories that we release to Dropbox, I also don't think it is necessary to run `make_provenance()` in a separate step. The relevant information will already be recorded in the state of repo log.

* I'm not sure I see the need for recording the contents of existing provenance files. If there's a need for this I'm missing let me know.

* Per @stanfordquan's comment [here](https://github.com/gslab-econ/template/issues/86#issuecomment-327364825), I think these problems are addressed since in what I'm proposing we will not need to compare one provenance file to another. The case where we would do this is if we're having trouble recreating output we would compare the current state of the inputs to the state of the inputs on the last commit; here it's fine if we are using a subset of what's in release.

* If we follow what I'm proposing, it seems like we may want to change the naming a bit. I'd think about changing `make_provenance()` to something like `state_of_directory()`. I'd suggest what we record in /release/ is called state_of_inputs.log and state_of_repo.log. 

Sorry if this is a deviation from previous instructions or if previous instructions were not clear. This stuff is only coming into focus for me now.

**Comment by stanfordquan** [comment]
@aro

**Comment by stanfordquan** [comment]
@gentzkow That makes sense. Basically this function `state_of_directory()` should record all external resources used by a repo at each SCons run, but no more. 

In that case I have two questions:

1) `state_of_repo.log` doesn't currently apply to raw directories on DropBox that doesn't use SCons and are not GIt-versioned. Do you still want the current `make_provenance()` (renamed to `state_of_directory()` procedure on those directories? At the moment that procedure is the only log we keep on raw directories. Are you ok with there being no log?

2) For recording inputs, do we set a protocol on how compartmentalized it should be? I.e., if the user downloads the whole directories (with code) `upstream_raw` and `upstream_derived` to `build/external`, do we ask the user to specify `build/external/upstream_raw` and `build/external/upstream_derived` separately or just `build/external`? This is not a coding question as much as a "template" question, since the code should be generalized to both uses.

**Comment by arosenbe** [comment]
@stanfordquan, my thought on 2 is that we use paths from the parsed `config_*.yaml` files. The user needs to supply the dictionary produced by parsing and the keys for the paths to record. We'll need one call and one list of keys for each yaml.

I'm in favor of adding new lines to the SConstruct that execute `state_of_directory()` at the beginning of the build. It shouldn't take more than four lines of code plus a comment.

We could alternatively incorporate `state_of_directory` into the SCons debrief (run at the end of each build). This would require only two lines of code.

**Comment by gentzkow** [comment]
Hmm. More good things to clarify.

* What I had in mind for the `state_of_directory()` name is that this is a general purpose function that takes a directory as input and produces a log of directory contents as output. This function can then be used, e.g., by our SConstruct. I like the idea of having this run at the beginning rather than the end.

* I had been under the impression we were dropping the `/build/external/` step entirely and just having the code point to the local paths specified in `config_*.yaml`. I think we should record the state of all such paths that are inputs to the code. We will want to make sure we have a way of differentiating such paths in the .yaml files.

* I do not think this need to be run for raw directories on Dropbox. Their provenance is documented in their readmes. What we are trying to achieve is that we know the inputs used to produce all subsequent output. (You could imagine running `state_of_directory()` on `/orig/` in cases where the raw directory includes code; that would be fine but I'd vote we try to get by without it for now.)

**Comment by arosenbe** [comment]
PR in #87

**Comment by arosenbe** [comment]
PR passed at #87. Summary comment:
* Store input files/directories in `config_*.yaml` under `input` key.
* All entries under this key have their contents recorded to `state_of_input.log` at the start of each build using the new `record_dir` function from gslab-econ/gslab_python#131. 
* Config yaml files are now parsed by `config/configuration.py`. Their contents is stored in the  `PATHS` dictionary, and each file has a key (either `global` or `user`) for its own nested dictionary. 
* Here's a nice description of the change to path-calling behavior. 
> We now parse config yaml files in our configuration step. We store each file's contents as a dictionary nested within the `PATHS` dictionary and accessible from the `global` or `user` key. To update from the 4.0.0 default, change all instances of `PATHS` to `PATHS['global']`.
